export interface CommonFields {
  Title?: string,
	'Other title'?: string,
  Surname?: string,
	'Other names'?: string,
  'AtW ref number'?: string,
  'Email address'?: string,
  'From day'?: string,
  'From month'?: string,
  'From year'?: string,
  'To day'?: string,
  'To month'?: string,
  'To year'?: string,
  'Their name'?: string,
  'Their position'?: string,
  'Their signature day'?: string,
  'Their signature month'?: string,
  'Their signature year'?: string,
  'Their signature'?: string,
  'Company name and address'?: string,
  'Payment made to'?: string,
  'Your name'?: string,
  'Your signature day'?: string,
  'Your signature month'?: string,
  'Your signature year'?: string,
  'Your signature'?: string,
  'Return details'?: string
}

export interface SupportWorker extends CommonFields {
  'Total hours'?: string,
  'Total costs'?: string,
  'Additional costs'?: string,
  'Employer contribution'?: string,
  'Amount claimed'?: string,

  'Date 1'?: string,
  'Date 2'?: string,
  'Date 3'?: string,
  'Date 4'?: string,
  'Date 5'?: string,
  'Date 6'?: string,
  'Date 7'?: string,
  'Date 8'?: string,
  'Date 9'?: string,
  'Date 10'?: string,
  'Date 11'?: string,
  'Date 12'?: string,
  'Date 13'?: string,
  'Date 14'?: string,
  'Date 15'?: string,
  'Date 16'?: string,
  'Date 17'?: string,
  'Date 18'?: string,
  'Date 19'?: string,
  'Date 20'?: string,
  'Date 21'?: string,
  'Date 22'?: string,
  'Date 23'?: string,
  'Date 24'?: string,
  'Date 25'?: string,
  'Date 26'?: string,
  'Date 27'?: string,
  'Date 28'?: string,
  'Date 29'?: string,
  'Date 30'?: string,
  'Date 31'?: string,

  'Hours claimed 1'?: string,
  'Hours claimed 2'?: string,
  'Hours claimed 3'?: string,
  'Hours claimed 4'?: string,
  'Hours claimed 5'?: string,
  'Hours claimed 6'?: string,
  'Hours claimed 7'?: string,
  'Hours claimed 8'?: string,
  'Hours claimed 9'?: string,
  'Hours claimed 10'?: string,
  'Hours claimed 11'?: string,
  'Hours claimed 12'?: string,
  'Hours claimed 13'?: string,
  'Hours claimed 14'?: string,
  'Hours claimed 15'?: string,
  'Hours claimed 16'?: string,
  'Hours claimed 17'?: string,
  'Hours claimed 18'?: string,
  'Hours claimed 19'?: string,
  'Hours claimed 20'?: string,
  'Hours claimed 21'?: string,
  'Hours claimed 22'?: string,
  'Hours claimed 23'?: string,
  'Hours claimed 24'?: string,
  'Hours claimed 25'?: string,
  'Hours claimed 26'?: string,
  'Hours claimed 27'?: string,
  'Hours claimed 28'?: string,
  'Hours claimed 29'?: string,
  'Hours claimed 30'?: string,
  'Hours claimed 31'?: string
}

export interface TravelToWork extends CommonFields {
  'How many days work each week'?: string,
  'Been at work all these days?'?: 'Yes' | 'No',
  'Total number of taxi journeys'?: string,
  'Total number of taxi journeys again'?: string,
  'Cost per journey or cost per mile'?: string,
  'Total cost'?: string,
  'Your contribution'?: string,
  'Other contributions'?: string,
  'Amount claimed'?: string,

  'Claimed 1'?: string,
  'Claimed 2'?: string,
  'Claimed 3'?: string,
  'Claimed 4'?: string,
  'Claimed 5'?: string,
  'Claimed 6'?: string,
  'Claimed 7'?: string,
  'Claimed 8'?: string,
  'Claimed 9'?: string,
  'Claimed 10'?: string,
  'Claimed 11'?: string,
  'Claimed 12'?: string,
  'Claimed 13'?: string,
  'Claimed 14'?: string,
  'Claimed 15'?: string,
  'Claimed 16'?: string,
  'Claimed 17'?: string,
  'Claimed 18'?: string,
  'Claimed 19'?: string,
  'Claimed 20'?: string,
  'Claimed 21'?: string,
  'Claimed 22'?: string,
  'Claimed 23'?: string,
  'Claimed 24'?: string,
  'Claimed 25'?: string,
  'Claimed 26'?: string,
  'Claimed 27'?: string,
  'Claimed 28'?: string,
  'Claimed 29'?: string,
  'Claimed 30'?: string,
  'Claimed 31'?: string,

  'Date 1'?: string,
  'Date 2'?: string,
  'Date 3'?: string,
  'Date 4'?: string,
  'Date 5'?: string,
  'Date 6'?: string,
  'Date 7'?: string,
  'Date 8'?: string,
  'Date 9'?: string,
  'Date 10'?: string,
  'Date 11'?: string,
  'Date 12'?: string,
  'Date 13'?: string,
  'Date 14'?: string,
  'Date 15'?: string,
  'Date 16'?: string,
  'Date 17'?: string,
  'Date 18'?: string,
  'Date 19'?: string,
  'Date 20'?: string,
  'Date 21'?: string,
  'Date 22'?: string,
  'Date 23'?: string,
  'Date 24'?: string,
  'Date 25'?: string,
  'Date 26'?: string,
  'Date 27'?: string,
  'Date 28'?: string,
  'Date 29'?: string,
  'Date 30'?: string,
  'Date 31'?: string
}